collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.6810777
  brandStrength: 0.6809919
  lightness: 0.7338186
  brandColors:
    - '#010100'
    - '#A59274'
    - '#D7770B'
    - '#572617'
    - '#A5500E'
  rhythmicContrast: 1
layout_spectrum: 0.2581454
name: Stephenbaumanavailableworks
