layout_spectrum: 0.7374687
color:
  saturation: 0.9110832
  lightness: 0.7338186
  brandStrength: 0.6809919
  brandColors:
    - '#010100'
    - '#A59274'
    - '#D7770B'
    - '#572617'
    - '#A5500E'
  rhythmicContrast: 0.7779776
typography_spectrum: 1
name: Stephenbaumanavailableworks
